
library globals;
import 'package:flutter/material.dart';

class CurrencyPickUtils {
  static CcyCountry getCountryByIsoCode(String isoCode) {
    try {
      return ccycountryList.firstWhere(
        (country) => country.isoCode.toLowerCase() == isoCode.toLowerCase(),
      );
    } catch (error) {
      throw Exception("The initialValue provided is not a supported iso code!");
    }
  }

  static CcyCountry getCountryByCurrencyCode(String currencyCode) {
    try {
      return ccycountryList.firstWhere(
        (country) => country.currencyCode.toLowerCase() == currencyCode.toLowerCase(),
      );
    } catch (error) {
      throw Exception(
          "The initialValue provided is not a supported country code!");
    }
  }


  static String getFlagImageAssetPath(String isoCode) {
    return "assets/ccycntry/${isoCode.toLowerCase()}.png";
  }

  static Widget getDefaultFlagImage(CcyCountry country) {
    return Image.asset(
      CurrencyPickUtils.getFlagImageAssetPath(country.isoCode),
      height: 20.0,
      width: 30.0,
      fit: BoxFit.fill,
    );
  }
}

class CcyCountry {
  final String name;
  final String isoCode;
  final String iso3Code;
  final String currencyCode;
  final String currencyName;
  CcyCountry({required this.isoCode, required this.iso3Code, required this.currencyCode, required this.currencyName, required this.name});

  factory CcyCountry.fromMap(Map<String, String> map) => CcyCountry(
        name: map['name']!,
        isoCode: map['isoCode']!,
        iso3Code: map['iso3Code']!,
        currencyCode: map['currencyCode']!,
        currencyName: map['currencyName']!,
      );
}

final List<CcyCountry> ccycountryList = [
  CcyCountry(
    isoCode: "AF",
    currencyCode: "AFN",
    currencyName: "Afghan afghani",
    name: "Afghanistan",
    iso3Code: "AFG",
  ),
  CcyCountry(
    isoCode: "AX",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Åland Islands",
    iso3Code: "ALA",
  ),
  CcyCountry(
    isoCode: "AL",
    currencyCode: "ALL",
    currencyName: "Albanian lek",
    name: "Albania",
    iso3Code: "ALB",
  ),
  CcyCountry(
    isoCode: "DZ",
    currencyCode: "DZD",
    currencyName: "Algerian dinar",
    name: "Algeria",
    iso3Code: "DZA",
  ),
  CcyCountry(
    isoCode: "AS",
    currencyCode: "USD",
    currencyName: "United State Dollar",
    name: "American Samoa",
    iso3Code: "ASM",
  ),
  CcyCountry(
    isoCode: "AD",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Andorra",
    iso3Code: "AND",
  ),
  CcyCountry(
    isoCode: "AO",
    currencyCode: "AOA",
    currencyName: "Angolan kwanza",
    name: "Angola",
    iso3Code: "AGO",
  ),
  CcyCountry(
    isoCode: "AI",
    currencyCode: "XCD",
    currencyName: "East Caribbean dollar",
    name: "Anguilla",
    iso3Code: "AIA",
  ),
  CcyCountry(
    isoCode: "AQ",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Antarctica",
    iso3Code: "ATA",
  ),
  CcyCountry(
    isoCode: "AG",
    currencyCode: "XCD",
    currencyName: "East Caribbean dollar",
    name: "Antigua and Barbuda",
    iso3Code: "ATG",
  ),
  CcyCountry(
    isoCode: "AR",
    currencyCode: "ARS",
    currencyName: "Argentine peso",
    name: "Argentina",
    iso3Code: "ARG",
  ),
  CcyCountry(
    isoCode: "AM",
    currencyCode: "AMD",
    currencyName: "Armenian dram",
    name: "Armenia",
    iso3Code: "ARM",
  ),
  CcyCountry(
    isoCode: "AW",
    currencyCode: "AWG",
    currencyName: "Aruban florin",
    name: "Aruba",
    iso3Code: "ABW",
  ),
  CcyCountry(
    isoCode: "AU",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Australia",
    iso3Code: "AUS",
  ),
  CcyCountry(
    isoCode: "AT",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Austria",
    iso3Code: "AUT",
  ),
  CcyCountry(
    isoCode: "AZ",
    currencyCode: "AZN",
    currencyName: "Azerbaijani manat",
    name: "Azerbaijan",
    iso3Code: "AZE",
  ),
  CcyCountry(
    isoCode: "BS",
    currencyCode: "BSD",
    currencyName: "Bahamian dollar",
    name: "Bahamas",
    iso3Code: "BHS",
  ),
  CcyCountry(
    isoCode: "BH",
    currencyCode: "BHD",
    currencyName: "Bahraini dinar",
    name: "Bahrain",
    iso3Code: "BHR",
  ),
  CcyCountry(
    isoCode: "BD",
    currencyCode: "BDT",
    currencyName: "Bangladeshi taka",
    name: "Bangladesh",
    iso3Code: "BGD",
  ),
  CcyCountry(
    isoCode: "BB",
    currencyCode: "BBD",
    currencyName: "Barbadian dollar",
    name: "Barbados",
    iso3Code: "BRB",
  ),
  CcyCountry(
    isoCode: "BY",
    currencyCode: "BYN",
    currencyName: "New Belarusian ruble",
    name: "Belarus",
    iso3Code: "BLR",
  ),
  CcyCountry(
    isoCode: "BE",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Belgium",
    iso3Code: "BEL",
  ),
  CcyCountry(
    isoCode: "BZ",
    currencyCode: "BZD",
    currencyName: "Belize dollar",
    name: "Belize",
    iso3Code: "BLZ",
  ),
  CcyCountry(
    isoCode: "BJ",
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    name: "Benin",
    iso3Code: "BEN",
  ),
  CcyCountry(
    isoCode: "BM",
    currencyCode: "BMD",
    currencyName: "Bermudian dollar",
    name: "Bermuda",
    iso3Code: "BMU",
  ),
  CcyCountry(
    isoCode: "BT",
    currencyCode: "BTN",
    currencyName: "Bhutanese ngultrum",
    name: "Bhutan",
    iso3Code: "BTN",
  ),
  CcyCountry(
    isoCode: "BO",
    currencyCode: "BOB",
    currencyName: "Bolivian boliviano",
    name: "Bolivia (Plurinational State of)",
    iso3Code: "BOL",
  ),
  CcyCountry(
    isoCode: "BQ",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Bonaire, Sint Eustatius and Saba",
    iso3Code: "BES",
  ),
  CcyCountry(
    isoCode: "BA",
    currencyCode: "BAM",
    currencyName: "Bosnia and Herzegovina convertible mark",
    name: "Bosnia and Herzegovina",
    iso3Code: "BIH",
  ),
  CcyCountry(
    isoCode: "BW",
    currencyCode: "BWP",
    currencyName: "Botswana pula",
    name: "Botswana",
    iso3Code: "BWA",
  ),
  CcyCountry(
    isoCode: "BV",
    currencyCode: "NOK",
    currencyName: "Norwegian krone",
    name: "Bouvet Island",
    iso3Code: "BVT",
  ),
  CcyCountry(
    isoCode: "BR",
    currencyCode: "BRL",
    currencyName: "Brazilian real",
    name: "Brazil",
    iso3Code: "BRA",
  ),
  CcyCountry(
    isoCode: "IO",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "British Indian Ocean Territory",
    iso3Code: "IOT",
  ),
  CcyCountry(
    isoCode: "VG",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Virgin Islands (British)",
    iso3Code: "VGB",
  ),
  CcyCountry(
    isoCode: "VI",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Virgin Islands (U.S.)",
    iso3Code: "VIR",
  ),
  CcyCountry(
    isoCode: "BN",
    currencyCode: "BND",
    currencyName: "Brunei dollar",
    name: "Brunei Darussalam",
    iso3Code: "BRN",
  ),
  CcyCountry(
    isoCode: "BG",
    currencyCode: "BGN",
    currencyName: "Bulgarian lev",
    name: "Bulgaria",
    iso3Code: "BGR",
  ),
  CcyCountry(
    isoCode: "BF",
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    name: "Burkina Faso",
    iso3Code: "BFA",
  ),
  CcyCountry(
    isoCode: "BI",
    currencyCode: "BIF",
    currencyName: "Burundian franc",
    name: "Burundi",
    iso3Code: "BDI",
  ),
  CcyCountry(
    isoCode: "KH",
    currencyCode: "KHR",
    currencyName: "Cambodian riel",
    name: "Cambodia",
    iso3Code: "KHM",
  ),
  CcyCountry(
    isoCode: "CM",
    currencyCode: "XAF",
    currencyName: "Central African CFA franc",
    name: "Cameroon",
    iso3Code: "CMR",
  ),
  CcyCountry(
    isoCode: "CA",
    currencyCode: "CAD",
    currencyName: "Canadian dollar",
    name: "Canada",
    iso3Code: "CAN",
  ),
  CcyCountry(
    isoCode: "CV",
    currencyCode: "CVE",
    currencyName: "Cape Verdean escudo",
    name: "Cabo Verde",
    iso3Code: "CPV",
  ),
  CcyCountry(
    isoCode: "KY",
    currencyCode: "KYD",
    currencyName: "Cayman Islands dollar",
    name: "Cayman Islands",
    iso3Code: "CYM",
  ),
  CcyCountry(
    isoCode: "CF",
    currencyCode: "XAF",
    currencyName: "Central African CFA franc",
    name: "Central African Republic",
    iso3Code: "CAF",
  ),
  CcyCountry(
    isoCode: "TD",
    currencyCode: "XAF",
    currencyName: "Central African CFA franc",
    name: "Chad",
    iso3Code: "TCD",
  ),
  CcyCountry(
    isoCode: "CL",
    currencyCode: "CLP",
    currencyName: "Chilean peso",
    name: "Chile",
    iso3Code: "CHL",
  ),
  CcyCountry(
    isoCode: "CN",
    currencyCode: "CNY",
    currencyName: "Chinese yuan",
    name: "China",
    iso3Code: "CHN",
  ),
  CcyCountry(
    isoCode: "CX",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Christmas Island",
    iso3Code: "CXR",
  ),
  CcyCountry(
    isoCode: "CC",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Cocos (Keeling) Islands",
    iso3Code: "CCK",
  ),
  CcyCountry(
    isoCode: "CO",
    currencyCode: "COP",
    currencyName: "Colombian peso",
    name: "Colombia",
    iso3Code: "COL",
  ),
  CcyCountry(
    isoCode: "KM",
    currencyCode: "KMF",
    currencyName: "Comorian franc",
    name: "Comoros",
    iso3Code: "COM",
  ),
  CcyCountry(
    isoCode: "CG",
    currencyCode: "XAF",
    currencyName: "Central African CFA franc",
    name: "Congo",
    iso3Code: "COG",
  ),
  CcyCountry(
    isoCode: "CD",
    currencyCode: "CDF",
    currencyName: "Congolese franc",
    name: "Congo (Democratic Republic of the)",
    iso3Code: "COD",
  ),
  CcyCountry(
    isoCode: "CK",
    currencyCode: "NZD",
    currencyName: "New Zealand dollar",
    name: "Cook Islands",
    iso3Code: "COK",
  ),
  CcyCountry(
    isoCode: "CR",
    currencyCode: "CRC",
    currencyName: "Costa Rican colón",
    name: "Costa Rica",
    iso3Code: "CRI",
  ),
  CcyCountry(
    isoCode: "HR",
    currencyCode: "HRK",
    currencyName: "Croatian kuna",
    name: "Croatia",
    iso3Code: "HRV",
  ),
  CcyCountry(
    isoCode: "CU",
    currencyCode: "CUC",
    currencyName: "Cuban convertible peso",
    name: "Cuba",
    iso3Code: "CUB",
  ),
  CcyCountry(
    isoCode: "CW",
    currencyCode: "ANG",
    currencyName: "Netherlands Antillean guilder",
    name: "Curaçao",
    iso3Code: "CUW",
  ),
  CcyCountry(
    isoCode: "CY",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Cyprus",
    iso3Code: "CYP",
  ),
  CcyCountry(
    isoCode: "CZ",
    currencyCode: "CZK",
    currencyName: "Czech koruna",
    name: "Czech Republic",
    iso3Code: "CZE",
  ),
  CcyCountry(
    isoCode: "DK",
    currencyCode: "DKK",
    currencyName: "Danish krone",
    name: "Denmark",
    iso3Code: "DNK",
  ),
  CcyCountry(
    isoCode: "DJ",
    currencyCode: "DJF",
    currencyName: "Djiboutian franc",
    name: "Djibouti",
    iso3Code: "DJI",
  ),
  CcyCountry(
    isoCode: "DM",
    currencyCode: "XCD",
    currencyName: "East Caribbean dollar",
    name: "Dominica",
    iso3Code: "DMA",
  ),
  CcyCountry(
    isoCode: "DO",
    currencyCode: "DOP",
    currencyName: "Dominican peso",
    name: "Dominican Republic",
    iso3Code: "DOM",
  ),
  CcyCountry(
    isoCode: "EC",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Ecuador",
    iso3Code: "ECU",
  ),
  CcyCountry(
    isoCode: "EG",
    currencyCode: "EGP",
    currencyName: "Egyptian pound",
    name: "Egypt",
    iso3Code: "EGY",
  ),
  CcyCountry(
    isoCode: "SV",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "El Salvador",
    iso3Code: "SLV",
  ),
  CcyCountry(
    isoCode: "GQ",
    currencyCode: "XAF",
    currencyName: "Central African CFA franc",
    name: "Equatorial Guinea",
    iso3Code: "GNQ",
  ),
  CcyCountry(
    isoCode: "ER",
    currencyCode: "ERN",
    currencyName: "Eritrean nakfa",
    name: "Eritrea",
    iso3Code: "ERI",
  ),
  CcyCountry(
    isoCode: "EE",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Estonia",
    iso3Code: "EST",
  ),
  CcyCountry(
    isoCode: "ET",
    currencyCode: "ETB",
    currencyName: "Ethiopian birr",
    name: "Ethiopia",
    iso3Code: "ETH",
  ),
  CcyCountry(
    isoCode: "FK",
    currencyCode: "FKP",
    currencyName: "Falkland Islands pound",
    name: "Falkland Islands (Malvinas)",
    iso3Code: "FLK",
  ),
  CcyCountry(
    isoCode: "FO",
    currencyCode: "DKK",
    currencyName: "Danish krone",
    name: "Faroe Islands",
    iso3Code: "FRO",
  ),
  CcyCountry(
    isoCode: "FJ",
    currencyCode: "FJD",
    currencyName: "Fijian dollar",
    name: "Fiji",
    iso3Code: "FJI",
  ),
  CcyCountry(
    isoCode: "FI",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Finland",
    iso3Code: "FIN",
  ),
  CcyCountry(
    isoCode: "FR",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "France",
    iso3Code: "FRA",
  ),
  CcyCountry(
    isoCode: "GF",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "French Guiana",
    iso3Code: "GUF",
  ),
  CcyCountry(
    isoCode: "PF",
    currencyCode: "XPF",
    currencyName: "CFP franc",
    name: "French Polynesia",
    iso3Code: "PYF",
  ),
  CcyCountry(
    isoCode: "TF",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "French Southern Territories",
    iso3Code: "ATF",
  ),
  CcyCountry(
    isoCode: "GA",
    currencyCode: "XAF",
    currencyName: "Central African CFA franc",
    name: "Gabon",
    iso3Code: "GAB",
  ),
  CcyCountry(
    isoCode: "GM",
    currencyCode: "GMD",
    currencyName: "Gambian dalasi",
    name: "Gambia",
    iso3Code: "GMB",
  ),
  CcyCountry(
    isoCode: "GE",
    currencyCode: "GEL",
    currencyName: "Georgian Lari",
    name: "Georgia",
    iso3Code: "GEO",
  ),
  CcyCountry(
    isoCode: "DE",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Germany",
    iso3Code: "DEU",
  ),
  CcyCountry(
    isoCode: "GH",
    currencyCode: "GHS",
    currencyName: "Ghanaian cedi",
    name: "Ghana",
    iso3Code: "GHA",
  ),
  CcyCountry(
    isoCode: "GI",
    currencyCode: "GIP",
    currencyName: "Gibraltar pound",
    name: "Gibraltar",
    iso3Code: "GIB",
  ),
  CcyCountry(
    isoCode: "GR",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Greece",
    iso3Code: "GRC",
  ),
  CcyCountry(
    isoCode: "GL",
    currencyCode: "DKK",
    currencyName: "Danish krone",
    name: "Greenland",
    iso3Code: "GRL",
  ),
  CcyCountry(
    isoCode: "GD",
    currencyCode: "XCD",
    currencyName: "East Caribbean dollar",
    name: "Grenada",
    iso3Code: "GRD",
  ),
  CcyCountry(
    isoCode: "GP",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Guadeloupe",
    iso3Code: "GLP",
  ),
  CcyCountry(
    isoCode: "GU",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Guam",
    iso3Code: "GUM",
  ),
  CcyCountry(
    isoCode: "GT",
    currencyCode: "GTQ",
    currencyName: "Guatemalan quetzal",
    name: "Guatemala",
    iso3Code: "GTM",
  ),
  CcyCountry(
    isoCode: "GG",
    currencyCode: "GBP",
    currencyName: "British pound",
    name: "Guernsey",
    iso3Code: "GGY",
  ),
  CcyCountry(
    isoCode: "GN",
    currencyCode: "GNF",
    currencyName: "Guinean franc",
    name: "Guinea",
    iso3Code: "GIN",
  ),
  CcyCountry(
    isoCode: "GW",
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    name: "Guinea-Bissau",
    iso3Code: "GNB",
  ),
  CcyCountry(
    isoCode: "GY",
    currencyCode: "GYD",
    currencyName: "Guyanese dollar",
    name: "Guyana",
    iso3Code: "GUY",
  ),
  CcyCountry(
    isoCode: "HT",
    currencyCode: "HTG",
    currencyName: "Haitian gourde",
    name: "Haiti",
    iso3Code: "HTI",
  ),
  CcyCountry(
    isoCode: "HM",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Heard Island and McDonald Islands",
    iso3Code: "HMD",
  ),
  CcyCountry(
    isoCode: "VA",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Holy See",
    iso3Code: "VAT",
  ),
  CcyCountry(
    isoCode: "HN",
    currencyCode: "HNL",
    currencyName: "Honduran lempira",
    name: "Honduras",
    iso3Code: "HND",
  ),
  CcyCountry(
    isoCode: "HK",
    currencyCode: "HKD",
    currencyName: "Hong Kong dollar",
    name: "Hong Kong",
    iso3Code: "HKG",
  ),
  CcyCountry(
    isoCode: "HU",
    currencyCode: "HUF",
    currencyName: "Hungarian forint",
    name: "Hungary",
    iso3Code: "HUN",
  ),
  CcyCountry(
    isoCode: "IS",
    currencyCode: "ISK",
    currencyName: "Icelandic króna",
    name: "Iceland",
    iso3Code: "ISL",
  ),
  CcyCountry(
    isoCode: "IN",
    currencyCode: "INR",
    currencyName: "Indian rupee",
    name: "India",
    iso3Code: "IND",
  ),
  CcyCountry(
    isoCode: "ID",
    currencyCode: "IDR",
    currencyName: "Indonesian rupiah",
    name: "Indonesia",
    iso3Code: "IDN",
  ),
  CcyCountry(
    isoCode: "CI",
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    name: "Côte d'Ivoire",
    iso3Code: "CIV",
  ),
  CcyCountry(
    isoCode: "IR",
    currencyCode: "IRR",
    currencyName: "Iranian rial",
    name: "Iran (Islamic Republic of)",
    iso3Code: "IRN",
  ),
  CcyCountry(
    isoCode: "IQ",
    currencyCode: "IQD",
    currencyName: "Iraqi dinar",
    name: "Iraq",
    iso3Code: "IRQ",
  ),
  CcyCountry(
    isoCode: "IE",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Ireland",
    iso3Code: "IRL",
  ),
  CcyCountry(
    isoCode: "IM",
    currencyCode: "GBP",
    currencyName: "British pound",
    name: "Isle of Man",
    iso3Code: "IMN",
  ),
  CcyCountry(
    isoCode: "IL",
    currencyCode: "ILS",
    currencyName: "Israeli new shekel",
    name: "Israel",
    iso3Code: "ISR",
  ),
  CcyCountry(
    isoCode: "IT",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Italy",
    iso3Code: "ITA",
  ),
  CcyCountry(
    isoCode: "JM",
    currencyCode: "JMD",
    currencyName: "Jamaican dollar",
    name: "Jamaica",
    iso3Code: "JAM",
  ),
  CcyCountry(
    isoCode: "JP",
    currencyCode: "JPY",
    currencyName: "Japanese yen",
    name: "Japan",
    iso3Code: "JPN",
  ),
  CcyCountry(
    isoCode: "JE",
    currencyCode: "GBP",
    currencyName: "British pound",
    name: "Jersey",
    iso3Code: "JEY",
  ),
  CcyCountry(
    isoCode: "JO",
    currencyCode: "JOD",
    currencyName: "Jordanian dinar",
    name: "Jordan",
    iso3Code: "JOR",
  ),
  CcyCountry(
    isoCode: "KZ",
    currencyCode: "KZT",
    currencyName: "Kazakhstani tenge",
    name: "Kazakhstan",
    iso3Code: "KAZ",
  ),
  CcyCountry(
    isoCode: "KE",
    currencyCode: "KES",
    currencyName: "Kenyan shilling",
    name: "Kenya",
    iso3Code: "KEN",
  ),
  CcyCountry(
    isoCode: "KI",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Kiribati",
    iso3Code: "KIR",
  ),
  CcyCountry(
    isoCode: "KW",
    currencyCode: "KWD",
    currencyName: "Kuwaiti dinar",
    name: "Kuwait",
    iso3Code: "KWT",
  ),
  CcyCountry(
    isoCode: "KG",
    currencyCode: "KGS",
    currencyName: "Kyrgyzstani som",
    name: "Kyrgyzstan",
    iso3Code: "KGZ",
  ),
  CcyCountry(
    isoCode: "LA",
    currencyCode: "LAK",
    currencyName: "Lao kip",
    name: "Lao People's Democratic Republic",
    iso3Code: "LAO",
  ),
  CcyCountry(
    isoCode: "LV",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Latvia",
    iso3Code: "LVA",
  ),
  CcyCountry(
    isoCode: "LB",
    currencyCode: "LBP",
    currencyName: "Lebanese pound",
    name: "Lebanon",
    iso3Code: "LBN",
  ),
  CcyCountry(
    isoCode: "LS",
    currencyCode: "LSL",
    currencyName: "Lesotho loti",
    name: "Lesotho",
    iso3Code: "LSO",
  ),
  CcyCountry(
    isoCode: "LR",
    currencyCode: "LRD",
    currencyName: "Liberian dollar",
    name: "Liberia",
    iso3Code: "LBR",
  ),
  CcyCountry(
    isoCode: "LY",
    currencyCode: "LYD",
    currencyName: "Libyan dinar",
    name: "Libya",
    iso3Code: "LBY",
  ),
  CcyCountry(
    isoCode: "LI",
    currencyCode: "CHF",
    currencyName: "Swiss franc",
    name: "Liechtenstein",
    iso3Code: "LIE",
  ),
  CcyCountry(
    isoCode: "LT",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Lithuania",
    iso3Code: "LTU",
  ),
  CcyCountry(
    isoCode: "LU",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Luxembourg",
    iso3Code: "LUX",
  ),
  CcyCountry(
    isoCode: "MO",
    currencyCode: "MOP",
    currencyName: "Macanese pataca",
    name: "Macao",
    iso3Code: "MAC",
  ),
  CcyCountry(
    isoCode: "MK",
    currencyCode: "MKD",
    currencyName: "Macedonian denar",
    name: "Macedonia (the former Yugoslav Republic of)",
    iso3Code: "MKD",
  ),
  CcyCountry(
    isoCode: "MG",
    currencyCode: "MGA",
    currencyName: "Malagasy ariary",
    name: "Madagascar",
    iso3Code: "MDG",
  ),
  CcyCountry(
    isoCode: "MW",
    currencyCode: "MWK",
    currencyName: "Malawian kwacha",
    name: "Malawi",
    iso3Code: "MWI",
  ),
  CcyCountry(
    isoCode: "MY",
    currencyCode: "MYR",
    currencyName: "Malaysian ringgit",
    name: "Malaysia",
    iso3Code: "MYS",
  ),
  CcyCountry(
    isoCode: "MV",
    currencyCode: "MVR",
    currencyName: "Maldivian rufiyaa",
    name: "Maldives",
    iso3Code: "MDV",
  ),
  CcyCountry(
    isoCode: "ML",
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    name: "Mali",
    iso3Code: "MLI",
  ),
  CcyCountry(
    isoCode: "MT",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Malta",
    iso3Code: "MLT",
  ),
  CcyCountry(
    isoCode: "MH",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Marshall Islands",
    iso3Code: "MHL",
  ),
  CcyCountry(
    isoCode: "MQ",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Martinique",
    iso3Code: "MTQ",
  ),
  CcyCountry(
    isoCode: "MR",
    currencyCode: "MRO",
    currencyName: "Mauritanian ouguiya",
    name: "Mauritania",
    iso3Code: "MRT",
  ),
  CcyCountry(
    isoCode: "MU",
    currencyCode: "MUR",
    currencyName: "Mauritian rupee",
    name: "Mauritius",
    iso3Code: "MUS",
  ),
  CcyCountry(
    isoCode: "YT",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Mayotte",
    iso3Code: "MYT",
  ),
  CcyCountry(
    isoCode: "MX",
    currencyCode: "MXN",
    currencyName: "Mexican peso",
    name: "Mexico",
    iso3Code: "MEX",
  ),
  CcyCountry(
    isoCode: "FM",
    currencyCode: "None",
    currencyName: "[D]",
    name: "Micronesia (Federated States of)",
    iso3Code: "FSM",
  ),
  CcyCountry(
    isoCode: "MD",
    currencyCode: "MDL",
    currencyName: "Moldovan leu",
    name: "Moldova (Republic of)",
    iso3Code: "MDA",
  ),
  CcyCountry(
    isoCode: "MC",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Monaco",
    iso3Code: "MCO",
  ),
  CcyCountry(
    isoCode: "MN",
    currencyCode: "MNT",
    currencyName: "Mongolian tögrög",
    name: "Mongolia",
    iso3Code: "MNG",
  ),
  CcyCountry(
    isoCode: "ME",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Montenegro",
    iso3Code: "MNE",
  ),
  CcyCountry(
    isoCode: "MS",
    currencyCode: "XCD",
    currencyName: "East Caribbean dollar",
    name: "Montserrat",
    iso3Code: "MSR",
  ),
  CcyCountry(
    isoCode: "MA",
    currencyCode: "MAD",
    currencyName: "Moroccan dirham",
    name: "Morocco",
    iso3Code: "MAR",
  ),
  CcyCountry(
    isoCode: "MZ",
    currencyCode: "MZN",
    currencyName: "Mozambican metical",
    name: "Mozambique",
    iso3Code: "MOZ",
  ),
  CcyCountry(
    isoCode: "MM",
    currencyCode: "MMK",
    currencyName: "Burmese kyat",
    name: "Myanmar",
    iso3Code: "MMR",
  ),
  CcyCountry(
    isoCode: "NA",
    currencyCode: "NAD",
    currencyName: "Namibian dollar",
    name: "Namibia",
    iso3Code: "NAM",
  ),
  CcyCountry(
    isoCode: "NR",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Nauru",
    iso3Code: "NRU",
  ),
  CcyCountry(
    isoCode: "NP",
    currencyCode: "NPR",
    currencyName: "Nepalese rupee",
    name: "Nepal",
    iso3Code: "NPL",
  ),
  CcyCountry(
    isoCode: "NL",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Netherlands",
    iso3Code: "NLD",
  ),
  CcyCountry(
    isoCode: "NC",
    currencyCode: "XPF",
    currencyName: "CFP franc",
    name: "New Caledonia",
    iso3Code: "NCL",
  ),
  CcyCountry(
    isoCode: "NZ",
    currencyCode: "NZD",
    currencyName: "New Zealand dollar",
    name: "New Zealand",
    iso3Code: "NZL",
  ),
  CcyCountry(
    isoCode: "NI",
    currencyCode: "NIO",
    currencyName: "Nicaraguan córdoba",
    name: "Nicaragua",
    iso3Code: "NIC",
  ),
  CcyCountry(
    isoCode: "NE",
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    name: "Niger",
    iso3Code: "NER",
  ),
  CcyCountry(
    isoCode: "NG",
    currencyCode: "NGN",
    currencyName: "Nigerian naira",
    name: "Nigeria",
    iso3Code: "NGA",
  ),
  CcyCountry(
    isoCode: "NU",
    currencyCode: "NZD",
    currencyName: "New Zealand dollar",
    name: "Niue",
    iso3Code: "NIU",
  ),
  CcyCountry(
    isoCode: "NF",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Norfolk Island",
    iso3Code: "NFK",
  ),
  CcyCountry(
    isoCode: "KP",
    currencyCode: "KPW",
    currencyName: "North Korean won",
    name: "Korea (Democratic People's Republic of)",
    iso3Code: "PRK",
  ),
  CcyCountry(
    isoCode: "MP",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Northern Mariana Islands",
    iso3Code: "MNP",
  ),
  CcyCountry(
    isoCode: "NO",
    currencyCode: "NOK",
    currencyName: "Norwegian krone",
    name: "Norway",
    iso3Code: "NOR",
  ),
  CcyCountry(
    isoCode: "OM",
    currencyCode: "OMR",
    currencyName: "Omani rial",
    name: "Oman",
    iso3Code: "OMN",
  ),
  CcyCountry(
    isoCode: "PK",
    currencyCode: "PKR",
    currencyName: "Pakistani rupee",
    name: "Pakistan",
    iso3Code: "PAK",
  ),
  CcyCountry(
    isoCode: "PW",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Palau",
    iso3Code: "PLW",
  ),
  CcyCountry(
    isoCode: "PS",
    currencyCode: "ILS",
    currencyName: "Israeli new sheqel",
    name: "Palestine, State of",
    iso3Code: "PSE",
  ),
  CcyCountry(
    isoCode: "PA",
    currencyCode: "PAB",
    currencyName: "Panamanian balboa",
    name: "Panama",
    iso3Code: "PAN",
  ),
  CcyCountry(
    isoCode: "PG",
    currencyCode: "PGK",
    currencyName: "Papua New Guinean kina",
    name: "Papua New Guinea",
    iso3Code: "PNG",
  ),
  CcyCountry(
    isoCode: "PY",
    currencyCode: "PYG",
    currencyName: "Paraguayan guaraní",
    name: "Paraguay",
    iso3Code: "PRY",
  ),
  CcyCountry(
    isoCode: "PE",
    currencyCode: "PEN",
    currencyName: "Peruvian sol",
    name: "Peru",
    iso3Code: "PER",
  ),
  CcyCountry(
    isoCode: "PH",
    currencyCode: "PHP",
    currencyName: "Philippine peso",
    name: "Philippines",
    iso3Code: "PHL",
  ),
  CcyCountry(
    isoCode: "PN",
    currencyCode: "NZD",
    currencyName: "New Zealand dollar",
    name: "Pitcairn",
    iso3Code: "PCN",
  ),
  CcyCountry(
    isoCode: "PL",
    currencyCode: "PLN",
    currencyName: "Polish z?oty",
    name: "Poland",
    iso3Code: "POL",
  ),
  CcyCountry(
    isoCode: "PT",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Portugal",
    iso3Code: "PRT",
  ),
  CcyCountry(
    isoCode: "PR",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Puerto Rico",
    iso3Code: "PRI",
  ),
  CcyCountry(
    isoCode: "QA",
    currencyCode: "QAR",
    currencyName: "Qatari riyal",
    name: "Qatar",
    iso3Code: "QAT",
  ),
  CcyCountry(
    isoCode: "XK",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Republic of Kosovo",
    iso3Code: "KOS",
  ),
  CcyCountry(
    isoCode: "RE",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Réunion",
    iso3Code: "REU",
  ),
  CcyCountry(
    isoCode: "RO",
    currencyCode: "RON",
    currencyName: "Romanian leu",
    name: "Romania",
    iso3Code: "ROU",
  ),
  CcyCountry(
    isoCode: "RU",
    currencyCode: "RUB",
    currencyName: "Russian ruble",
    name: "Russian Federation",
    iso3Code: "RUS",
  ),
  CcyCountry(
    isoCode: "RW",
    currencyCode: "RWF",
    currencyName: "Rwandan franc",
    name: "Rwanda",
    iso3Code: "RWA",
  ),
  CcyCountry(
    isoCode: "BL",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Saint Barthélemy",
    iso3Code: "BLM",
  ),
  CcyCountry(
    isoCode: "SH",
    currencyCode: "SHP",
    currencyName: "Saint Helena pound",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    iso3Code: "SHN",
  ),
  CcyCountry(
    isoCode: "KN",
    currencyCode: "XCD",
    currencyName: "East Caribbean dollar",
    name: "Saint Kitts and Nevis",
    iso3Code: "KNA",
  ),
  CcyCountry(
    isoCode: "LC",
    currencyCode: "XCD",
    currencyName: "East Caribbean dollar",
    name: "Saint Lucia",
    iso3Code: "LCA",
  ),
  CcyCountry(
    isoCode: "MF",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Saint Martin (French part)",
    iso3Code: "MAF",
  ),
  CcyCountry(
    isoCode: "PM",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Saint Pierre and Miquelon",
    iso3Code: "SPM",
  ),
  CcyCountry(
    isoCode: "VC",
    currencyCode: "XCD",
    currencyName: "East Caribbean dollar",
    name: "Saint Vincent and the Grenadines",
    iso3Code: "VCT",
  ),
  CcyCountry(
    isoCode: "WS",
    currencyCode: "WST",
    currencyName: "Samoan t?l?",
    name: "Samoa",
    iso3Code: "WSM",
  ),
  CcyCountry(
    isoCode: "SM",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "San Marino",
    iso3Code: "SMR",
  ),
  CcyCountry(
    isoCode: "ST",
    currencyCode: "STD",
    currencyName: "São Tomé and Príncipe dobra",
    name: "Sao Tome and Principe",
    iso3Code: "STP",
  ),
  CcyCountry(
    isoCode: "SA",
    currencyCode: "SAR",
    currencyName: "Saudi riyal",
    name: "Saudi Arabia",
    iso3Code: "SAU",
  ),
  CcyCountry(
    isoCode: "SN",
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    name: "Senegal",
    iso3Code: "SEN",
  ),
  CcyCountry(
    isoCode: "RS",
    currencyCode: "RSD",
    currencyName: "Serbian dinar",
    name: "Serbia",
    iso3Code: "SRB",
  ),
  CcyCountry(
    isoCode: "SC",
    currencyCode: "SCR",
    currencyName: "Seychellois rupee",
    name: "Seychelles",
    iso3Code: "SYC",
  ),
  CcyCountry(
    isoCode: "SL",
    currencyCode: "SLL",
    currencyName: "Sierra Leonean leone",
    name: "Sierra Leone",
    iso3Code: "SLE",
  ),
  CcyCountry(
    isoCode: "SG",
    currencyCode: "SGD",
    currencyName: "Singapore dollar",
    name: "Singapore",
    iso3Code: "SGP",
  ),
  CcyCountry(
    isoCode: "SX",
    currencyCode: "ANG",
    currencyName: "Netherlands Antillean guilder",
    name: "Sint Maarten (Dutch part)",
    iso3Code: "SXM",
  ),
  CcyCountry(
    isoCode: "SK",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Slovakia",
    iso3Code: "SVK",
  ),
  CcyCountry(
    isoCode: "SI",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Slovenia",
    iso3Code: "SVN",
  ),
  CcyCountry(
    isoCode: "SB",
    currencyCode: "SBD",
    currencyName: "Solomon Islands dollar",
    name: "Solomon Islands",
    iso3Code: "SLB",
  ),
  CcyCountry(
    isoCode: "SO",
    currencyCode: "SOS",
    currencyName: "Somali shilling",
    name: "Somalia",
    iso3Code: "SOM",
  ),
  CcyCountry(
    isoCode: "ZA",
    currencyCode: "ZAR",
    currencyName: "South African rand",
    name: "South Africa",
    iso3Code: "ZAF",
  ),
  CcyCountry(
    isoCode: "GS",
    currencyCode: "GBP",
    currencyName: "British pound",
    name: "South Georgia and the South Sandwich Islands",
    iso3Code: "SGS",
  ),
  CcyCountry(
    isoCode: "KR",
    currencyCode: "KRW",
    currencyName: "South Korean won",
    name: "Korea (Republic of)",
    iso3Code: "KOR",
  ),
  CcyCountry(
    isoCode: "SS",
    currencyCode: "SSP",
    currencyName: "South Sudanese pound",
    name: "South Sudan",
    iso3Code: "SSD",
  ),
  CcyCountry(
    isoCode: "ES",
    currencyCode: "EUR",
    currencyName: "Euro",
    name: "Spain",
    iso3Code: "ESP",
  ),
  CcyCountry(
    isoCode: "LK",
    currencyCode: "LKR",
    currencyName: "Sri Lankan rupee",
    name: "Sri Lanka",
    iso3Code: "LKA",
  ),
  CcyCountry(
    isoCode: "SD",
    currencyCode: "SDG",
    currencyName: "Sudanese pound",
    name: "Sudan",
    iso3Code: "SDN",
  ),
  CcyCountry(
    isoCode: "SR",
    currencyCode: "SRD",
    currencyName: "Surinamese dollar",
    name: "Suriname",
    iso3Code: "SUR",
  ),
  CcyCountry(
    isoCode: "SJ",
    currencyCode: "NOK",
    currencyName: "Norwegian krone",
    name: "Svalbard and Jan Mayen",
    iso3Code: "SJM",
  ),
  CcyCountry(
    isoCode: "SZ",
    currencyCode: "SZL",
    currencyName: "Swazi lilangeni",
    name: "Swaziland",
    iso3Code: "SWZ",
  ),
  CcyCountry(
    isoCode: "SE",
    currencyCode: "SEK",
    currencyName: "Swedish krona",
    name: "Sweden",
    iso3Code: "SWE",
  ),
  CcyCountry(
    isoCode: "CH",
    currencyCode: "CHF",
    currencyName: "Swiss franc",
    name: "Switzerland",
    iso3Code: "CHE",
  ),
  CcyCountry(
    isoCode: "SY",
    currencyCode: "SYP",
    currencyName: "Syrian pound",
    name: "Syrian Arab Republic",
    iso3Code: "SYR",
  ),
  CcyCountry(
    isoCode: "TW",
    currencyCode: "TWD",
    currencyName: "New Taiwan dollar",
    name: "Taiwan",
    iso3Code: "TWN",
  ),
  CcyCountry(
    isoCode: "TJ",
    currencyCode: "TJS",
    currencyName: "Tajikistani somoni",
    name: "Tajikistan",
    iso3Code: "TJK",
  ),
  CcyCountry(
    isoCode: "TZ",
    currencyCode: "TZS",
    currencyName: "Tanzanian shilling",
    name: "Tanzania, United Republic of",
    iso3Code: "TZA",
  ),
  CcyCountry(
    isoCode: "TH",
    currencyCode: "THB",
    currencyName: "Thai baht",
    name: "Thailand",
    iso3Code: "THA",
  ),
  CcyCountry(
    isoCode: "TL",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Timor-Leste",
    iso3Code: "TLS",
  ),
  CcyCountry(
    isoCode: "TG",
    currencyCode: "XOF",
    currencyName: "West African CFA franc",
    name: "Togo",
    iso3Code: "TGO",
  ),
  CcyCountry(
    isoCode: "TK",
    currencyCode: "NZD",
    currencyName: "New Zealand dollar",
    name: "Tokelau",
    iso3Code: "TKL",
  ),
  CcyCountry(
    isoCode: "TO",
    currencyCode: "TOP",
    currencyName: "Tongan pa?anga",
    name: "Tonga",
    iso3Code: "TON",
  ),
  CcyCountry(
    isoCode: "TT",
    currencyCode: "TTD",
    currencyName: "Trinidad and Tobago dollar",
    name: "Trinidad and Tobago",
    iso3Code: "TTO",
  ),
  CcyCountry(
    isoCode: "TN",
    currencyCode: "TND",
    currencyName: "Tunisian dinar",
    name: "Tunisia",
    iso3Code: "TUN",
  ),
  CcyCountry(
    isoCode: "TR",
    currencyCode: "TRY",
    currencyName: "Turkish lira",
    name: "Turkey",
    iso3Code: "TUR",
  ),
  CcyCountry(
    isoCode: "TM",
    currencyCode: "TMT",
    currencyName: "Turkmenistan manat",
    name: "Turkmenistan",
    iso3Code: "TKM",
  ),
  CcyCountry(
    isoCode: "TC",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "Turks and Caicos Islands",
    iso3Code: "TCA",
  ),
  CcyCountry(
    isoCode: "TV",
    currencyCode: "AUD",
    currencyName: "Australian dollar",
    name: "Tuvalu",
    iso3Code: "TUV",
  ),
  CcyCountry(
    isoCode: "UG",
    currencyCode: "UGX",
    currencyName: "Ugandan shilling",
    name: "Uganda",
    iso3Code: "UGA",
  ),
  CcyCountry(
    isoCode: "UA",
    currencyCode: "UAH",
    currencyName: "Ukrainian hryvnia",
    name: "Ukraine",
    iso3Code: "UKR",
  ),
  CcyCountry(
    isoCode: "AE",
    currencyCode: "AED",
    currencyName: "United Arab Emirates dirham",
    name: "United Arab Emirates",
    iso3Code: "ARE",
  ),
  CcyCountry(
    isoCode: "GB",
    currencyCode: "GBP",
    currencyName: "British pound",
    name: "United Kingdom of Great Britain and Northern Ireland",
    iso3Code: "GBR",
  ),
  CcyCountry(
    isoCode: "US",
    currencyCode: "USD",
    currencyName: "United States dollar",
    name: "United States of America",
    iso3Code: "USA",
  ),
  CcyCountry(
    isoCode: "UY",
    currencyCode: "UYU",
    currencyName: "Uruguayan peso",
    name: "Uruguay",
    iso3Code: "URY",
  ),
  CcyCountry(
    isoCode: "UZ",
    currencyCode: "UZS",
    currencyName: "Uzbekistani so'm",
    name: "Uzbekistan",
    iso3Code: "UZB",
  ),
  CcyCountry(
    isoCode: "VU",
    currencyCode: "VUV",
    currencyName: "Vanuatu vatu",
    name: "Vanuatu",
    iso3Code: "VUT",
  ),
  CcyCountry(
    isoCode: "VE",
    currencyCode: "VEF",
    currencyName: "Venezuelan bolívar",
    name: "Venezuela (Bolivarian Republic of)",
    iso3Code: "VEN",
  ),
  CcyCountry(
    isoCode: "VN",
    currencyCode: "VND",
    currencyName: "Vietnamese ??ng",
    name: "Viet Nam",
    iso3Code: "VNM",
  ),
  CcyCountry(
    isoCode: "WF",
    currencyCode: "XPF",
    currencyName: "CFP franc",
    name: "Wallis and Futuna",
    iso3Code: "WLF",
  ),
  CcyCountry(
    isoCode: "EH",
    currencyCode: "MAD",
    currencyName: "Moroccan dirham",
    name: "Western Sahara",
    iso3Code: "ESH",
  ),
  CcyCountry(
    isoCode: "YE",
    currencyCode: "YER",
    currencyName: "Yemeni rial",
    name: "Yemen",
    iso3Code: "YEM",
  ),
  CcyCountry(
    isoCode: "ZM",
    currencyCode: "ZMW",
    currencyName: "Zambian kwacha",
    name: "Zambia",
    iso3Code: "ZMB",
  ),
  CcyCountry(
    isoCode: "ZW",
    currencyCode: "BWP",
    currencyName: "Botswana pula",
    name: "Zimbabwe",
    iso3Code: "ZWE",
  ),
];



